### ISSUE TITLE
在使用图片压缩的时候报错的了

### ISSUE THREAD

**Issue by Reyfang** [joeyguo/gka#2]
我在使用图片压缩的时候报错如下：

> C:\WINDOWS\system32>gka -t C:\Users\xxx\Pictures\tinified
gka version:1.4.6
> - optimizing image..
>dir: C:\Users\xxx\Pictures\tinified
[ 'C:\\Users\\xxx\\Pictures\\tinified' ]
(node:11740) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 44): Error: Error in file: C:/Users/xxx/Pictures/tinified/0002.png
>ϵͳ�Ҳ���ָ����·����
>(node:11740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

node版本为V8.1.3，请问这个是我使用错了么？

**Comment by joeyguo** [comment]
@Reyfang hi，Reyfang，因为我这边无法复现，可否加一下我的QQ进一步了解情况 3201590286 ：D

**Comment by joeyguo** [comment]
解决方式：

1. npm root -g 
找到全局 node_modules 目录并删除 gka 目录

2. npm install -g gka 
重装gka
