### ISSUE TITLE
能限定图片尺寸吗，因为是以 px 为单位来定位背景的，不方便改变父级大小

### ISSUE THREAD

**Issue by foreverZ133** [joeyguo/gka#3]
当修改父级宽度时，旁边相连的 sprite 就出来了。
个人一般用 bg-size 的倍数，并用 % 为单位来定位背景。
我也不知道这样做对不对，但还是提一下吧。

**Comment by joeyguo** [comment]
@foreverZ133 

(1) 优先支持了百分比的 CSS 输出，可自适应的图像，欢迎尝鲜： gka@1.4.7-beta.1

``` bash
npm install -g gka@1.4.7-beta.1
```

输出：

xx_percent.html
xx-gka_percent.css

(2) 输出指定的图像尺寸，这个在规划中，欢迎关注

多谢反馈 💃
